import "./globals.css";

import type { Metadata } from "next";
import { PretendardFont } from "@/style/fonts";
import { ToastProvider } from "@/components/toast/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={PretendardFont.className + " text-black font-normal"}>
        <ToastProvider>{children}</ToastProvider>
        <div id="portal"></div>
      </body>
    </html>
  );
}
